import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    padding: 10,
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    flexDirection: 'row',
    marginHorizontal: 2,
    padding: 10,
  },
  viewOne: {
    display: "flex",
    flexDirection: "row",
    height: 60,
    width: "100%",
    backgroundColor: "#f9f7ff",
    justifyContent: "space-between",
    alignItems: "center",
  },
  imgOne: {
    width: 24,
    height: 24,
    margin: 15,
  },
  viewTwo: {
    backgroundColor: "#714dd9",
    borderWidth: 1,
    borderColor: "#714dd9",
    alignItems: "center",
    justifyContent: "center",
    width: 108,
    height: 48,
    marginRight: 20,
    paddingVertical: 15,
    borderRadius: 8,
  },
  textOne: { color: "#ffffff", fontSize: 18 },
  viewThree: {
    height: "100%",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "#f9f7ff",
  },
  viewFour: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  viewFive: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 8,
    padding: 20,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 2,
  },
  imgTwo: { width: 32, height: 48 },
  cards:{
    fontWeight: "bold",
    fontSize: 16,
    textAlign: "center",
  },
  img:{
    width: 24,
    height: 24,
    margin: 15,
  },
cards1:{
  fontSize: 13,
  textAlign: "center",
},
views:{
  margin: 20,
  backgroundColor: "white",
  borderRadius: 8,
  padding: 20,
  alignItems: "center",
  shadowColor: "#000",
  shadowOffset: {
    width: 0,
    height: 1,
  },
  shadowOpacity: 0.25,
  shadowRadius: 4,
  elevation: 2,
},
card2:{
  display: "flex",
  flexDirection: "row",
},
card3:{
  color: "#714DD9",
  fontSize: 14,
  fontWeight: "bold",
},
textFive:{
  height: 48,
  backgroundColor: "#ffffff",
  borderRadius: 8,
  borderWidth: 1,
  borderColor: "#d9d9d9",
  paddingLeft: 20,
  paddingRight: 20,
  marginLeft: 20,
  marginRight: 20,
},
textSix:{
  fontSize: 12,
  marginLeft: 20,
  marginRight: 20,
},
textEight:{
  display: "flex",
  flexDirection: "column",
  backgroundColor: "#ffffff",
  marginLeft: 20,
  marginRight: 20,
  borderRadius: 15,
},
viewDen:{
  color: "#714DD9",
  fontSize: 14,
  fontWeight: "bold",
},
textSeven:{
  display: "flex",
  width: "100%",
  paddingHorizontal: 20,
  paddingVertical: 5,
  flexDirection: "column",
},
textTen:{
  fontSize: 12,
  marginLeft: 20,
  marginRight: 20,
},
describe:{
  height: 150,
  backgroundColor: "#ffffff",
  paddingLeft: 20,
  paddingRight: 20,
  marginTop: 10,
},
describer:{
  fontSize: 12,
  marginLeft: 20,
  marginRight: 20,
},
viewHere:{
  display: "flex",
  flexDirection: "row",
  backgroundColor: "#ffffff",
  height: 67,
  width: "90%",
  paddingLeft: 2,
  paddingRight: 20,
  borderRadius: 5,
  justifyContent: "center",
  alignItems: "center",
  marginLeft: 20,
},
texter:{
  fontSize: 12,
  marginLeft: 20,
  marginRight: 20,
},
viewer:{
  display: "flex",
  flexDirection: "row",
  backgroundColor: "#ffffff",
  height: 48,
  width: 106,
  paddingLeft: 2,
  justifyContent: "center",
  alignItems: "center",
  marginLeft: 20,
},
texter1:{
  display: "flex",
  flexDirection: "column",
  paddingLeft: 20,
  paddingRight: 20,
  marginTop: 30,
},
viewing:{ height: 8 },
viewingOne:{
  flex: 1,
  marginTop: 10,
},
viewingTwo:{ fontSize: 18, fontWeight: "bold" },
viewee:{ height: 20 }
});
