export { Button } from "./Button";
export { Checkbox } from "./Checkbox";
export { Header } from "./Header";
export { Input } from "./Input";
export { Timepicker } from "./Timepicker";
export { BoxModal } from "./BoxModal";
// export { OtpInput } from "./OtpInput";
export { default as Header } from "./Header";
export { default as Input } from "./Input";
export { default as Button } from "./Button";
export { default as Tasks } from "./Tasks";
// export { default as Task } from "./Task";
export { default as SettingOption } from "./settings/SettingOption";
export {default as SettingCard} from "./settings/SettingCard";
