import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    padding: 10,
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  button: {
    flexDirection: "row",
    marginHorizontal: 2,
    padding: 10,
  },
  viewOne:{
    height: "100%",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    paddingTop: 50,
    paddingLeft:20,
    paddingRight:20,
    backgroundColor: "#ffffff",
  },
  viewTwo:{
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingRight: 20,
  },
  textOne:{ color: "#714DD9", fontSize: 14 },
  img:{
    flex: 3,
    width: "100%",
  },
  card:{
    flex: 1,
    alignItems: "center",
    paddingTop: 10,
    display: "flex",
    flexDirection: "column",
  },
  cards:{
    fontSize: 18,
    fontWeight: "bold",
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 8,
  },
  texts:{ fontSize: 14, paddingBottom: 5 },
  texter:{ fontSize: 14, paddingBottom: 20 },
  container:{
    height: "100%",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    paddingTop: 50,
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: "#ffffff",
  },
  container2:{
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingRight: 20,
  },
  container3:{
    flex: 1,
    alignItems: "center",
    paddingTop: 10,
    display: "flex",
    flexDirection: "column",
  },
  container4:{
    fontSize: 18,
    fontWeight: "bold",
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 8,
  },
});
